apiVersion: v1
kind: Service
metadata:
  name: model-gateway
  namespace: default
  labels:
    app: model-gateway
spec:
  type: ClusterIP
  selector:
    app: model-gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
